# fly.toml app configuration file generated for budget-bot-server on 2026-03-29T12:33:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'budget-bot-server'
primary_region = 'hkg'

[build]

[mounts]
  source = "wa_session"
  destination = "/app/.wwebjs_auth"

[http_service]
  internal_port = 1001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[deployment]
  strategy = "immediate"
