import { Model } from "mongoose";
import WAWebJS from "whatsapp-web.js";

import { ITransaction, Rekap, TotalTransactionRekap } from "../../types";
import { TRANSACTION_TYPE } from "../constants";

const rekapFormat = (month: string, year: string, outgoing: Number, incoming: Number, total: TotalTransactionRekap) => {
  const teksRekap = `
  📊 *REKAPITULASI: ${month.toUpperCase()} ${year}*
  ━━━━━━━━━━━━━━━━━━━━━━

  💰 *DATA KEUANGAN*
  📈 Pemasukan  : *Rp ${incoming.toLocaleString('id-ID')}*
  📉 Pengeluaran : *Rp ${outgoing.toLocaleString('id-ID')}*
  ──────────────────────

  📝 *STATISTIK AKTIVITAS*
  📥 Transaksi Masuk  : ${total.incoming}x
  📤 Transaksi Keluar : ${total.outgoing}x
  🔄 Total Aktivitas  : ${total.total}x

  ━━━━━━━━━━━━━━━━━━━━━━
  _Generated by BudgetBot_
  `.trim();
    

  return teksRekap;
}

export const transactionRecordCurrentMonth = async (
  userId: string,
  message: WAWebJS.Message,
  Transaction: Model<ITransaction>,
) => {
  let pengeluaran = 0;
  let pemasukan = 0;
  let jumlahTransaksiKeluar = 0;
  let jumlahTransaksiMasuk = 0;

  const getDate = new Date();
  const currentMonth = getDate.getMonth() + 1;
  const currentYear = getDate.getFullYear();

  const rekap = await Transaction.aggregate([
    {
      $match: {
        userId,
        $expr: {
          $and: [
            { $eq: [{ $month: "$date" }, currentMonth] },
            { $eq: [{ $year: "$date" }, currentYear] }
          ]
        }
      }
    },
    {
      $group: {
        _id: "$type",
        total: { $sum: "$amount" },
        count: { $sum: 1 }
      }
    }
  ]);

  rekap.forEach((item: Rekap) => {
    if (item._id === TRANSACTION_TYPE.OUT) {
      pengeluaran = item.total;
      jumlahTransaksiKeluar = item.count;
    } else if (item._id === TRANSACTION_TYPE.IN) {
      pemasukan = item.total;
      jumlahTransaksiMasuk = item.count;
    };
  });

  const longMonth = getDate.toLocaleString('id-ID', { month: 'long' });
  const jumlahTransaksi = jumlahTransaksiKeluar + jumlahTransaksiMasuk;

  if (jumlahTransaksi === 0) {
    message.reply(`📭 *Rekap ${longMonth} ${currentYear}*\n\nBelum ada transaksi yang dicatat bulan ini.`);
  } else {
    const totalTransaction = {
      outgoing: jumlahTransaksiKeluar,
      incoming: jumlahTransaksiMasuk,
      total: jumlahTransaksi
    }

    const recordTextFormat = rekapFormat(
      longMonth,
      currentYear.toString(),
      pengeluaran,
      pemasukan,
      totalTransaction
    );

    message.reply(recordTextFormat);
  }
}