import { Model } from "mongoose";
import type { WASocket } from "@whiskeysockets/baileys";

import {
  TRANSACTION_TYPE,
  CATEGORY_EMOJIS_EXPENSE,
  CATEGORY_EMOJIS_INCOME,
} from "../constants/index.js";
import { Transaction } from "../models/index.js";
import { ITransaction, Rekap, RekapItemType, TotalTransactionRekap } from "../types/index.js";
import { decrypt } from "./encryption.js";

const rekapFormat = (
  month: string,
  year: string,
  outgoing: number,
  incoming: number,
  total: TotalTransactionRekap,
  categoryBreakdown: string
): string => {
  const categorySection = categoryBreakdown ? `
  ${categoryBreakdown}  ──────────────────────` : '';

  const teksRekap = `
  📊 *REKAPITULASI: ${month.toUpperCase()} ${year}*
  ━━━━━━━━━━━━━━━━━━━━━━

  💰 *DATA KEUANGAN*
  📈 Pemasukan  : *Rp ${incoming.toLocaleString('id-ID')}*
  📉 Pengeluaran : *Rp ${outgoing.toLocaleString('id-ID')}*
  ──────────────────────${categorySection}

  📝 *STATISTIK AKTIVITAS*
  📥 Transaksi Masuk  : ${total.incoming}x
  📤 Transaksi Keluar : ${total.outgoing}x
  🔄 Total Aktivitas  : ${total.total}x

  ━━━━━━━━━━━━━━━━━━━━━━
  _Generated by BudgetBot_
  `.trim();

  return teksRekap;
}

export const transactionRecordCurrentMonth = async (
  userId: string,
  sock: WASocket,
  jid: string,
  Transaction: Model<ITransaction>,
): Promise<void> => {
  let pengeluaran = 0;
  let pemasukan = 0;
  let jumlahTransaksiKeluar = 0;
  let jumlahTransaksiMasuk = 0;

  const getDate = new Date();

  const currentMonth = parseInt(getDate.toLocaleString('id-ID', { month: 'numeric', timeZone: 'Asia/Jakarta' }));
  const currentYear = parseInt(getDate.toLocaleString('id-ID', { year: 'numeric', timeZone: 'Asia/Jakarta' }));

  const monthName = getDate.toLocaleString('id-ID', { month: 'long', timeZone: 'Asia/Jakarta' });
  
  const rekap = await Transaction.aggregate([
    {
      $match: {
        userId,
        $expr: {
          $and: [
            { $eq: [{ $month: "$date" }, currentMonth] },
            { $eq: [{ $year: "$date" }, currentYear] }
          ]
        }
      }
    },
    {
      $group: {
        _id: "$type",
        total: { $sum: "$amount" },
        count: { $sum: 1 }
      }
    }
  ]);

  rekap.forEach((item: Rekap) => {
    if (item._id === TRANSACTION_TYPE.OUT) {
      pengeluaran = item.total;
      jumlahTransaksiKeluar = item.count;
    } else if (item._id === TRANSACTION_TYPE.IN) {
      pemasukan = item.total;
      jumlahTransaksiMasuk = item.count;
    }
  });

  const longMonth = getDate.toLocaleString('id-ID', { 
    month: 'long',
    timeZone: 'Asia/Jakarta' 
  });
  const jumlahTransaksi = jumlahTransaksiKeluar + jumlahTransaksiMasuk;

  if (jumlahTransaksi === 0) {
    await sock.sendMessage(jid, {
      text: `📭 *Rekap ${longMonth} ${currentYear}*\n\nBelum ada transaksi yang dicatat bulan ini.`,
    });
  } else {
    const categoryRekap = await Transaction.aggregate([
      {
        $match: {
          userId,
          $expr: {
            $and: [
              { $eq: [{ $month: "$date" }, currentMonth] },
              { $eq: [{ $year: "$date" }, currentYear] }
            ]
          }
        }
      },
      {
        $group: {
          _id: { type: "$type", category: "$category" },
          total: { $sum: "$amount" }
        }
      },
      {
        $sort: { "_id.type": 1, total: -1 }
      }
    ]);

    let categoryBreakdownText = "";
    let lastType: string | undefined;
    categoryRekap.forEach((item: RekapItemType) => {
      if (item._id.type !== lastType) {
        lastType = item._id.type;
        categoryBreakdownText += item._id.type === TRANSACTION_TYPE.IN
          ? "  📁 *PEMASUKAN PER KATEGORI*\n"
          : "  📁 *PENGELUARAN PER KATEGORI*\n";
      }

      const categoryName = item._id.category || (item._id.type === TRANSACTION_TYPE.IN ? "Other Income" : "Other Expense");
      const emojiMap = item._id.type === TRANSACTION_TYPE.IN ? CATEGORY_EMOJIS_INCOME : CATEGORY_EMOJIS_EXPENSE;
      const emoji = emojiMap[categoryName as keyof typeof emojiMap] || "📦";
      const total = item._id.type === TRANSACTION_TYPE.IN ? pemasukan : pengeluaran;
      const percentage = total > 0 ? Math.round((item.total / total) * 100) : 0;
      categoryBreakdownText += `  ${emoji} ${categoryName}: *Rp ${item.total.toLocaleString('id-ID')}* (${percentage}%)\n`;
    });

    const totalTransaction: TotalTransactionRekap = {
      outgoing: jumlahTransaksiKeluar,
      incoming: jumlahTransaksiMasuk,
      total: jumlahTransaksi
    }

    const recordTextFormat = rekapFormat(
      monthName,
      currentYear.toString(),
      pengeluaran,
      pemasukan,
      totalTransaction,
      categoryBreakdownText
    );

    await sock.sendMessage(jid, { text: recordTextFormat });
  }
}

export const transactionHistoryBy = async (
  userId: string,
  match: RegExpMatchArray,
  sock: WASocket,
  jid: string, 
): Promise<void> => {
  if(!match) return;

  let getLimit = Math.min(parseInt(match[2] || '5'), 20);
  
  const findTransaction = await Transaction.find({userId}).sort({date: -1}).limit(getLimit);

  if (findTransaction.length === 0) {
    await sock.sendMessage(jid, { text: "📭 Belum ada catatan transaksii"});

    return
  }

  if (findTransaction.length < 5){ 
    getLimit = findTransaction.length;
  }

  let listTeks = `📝 *${getLimit} TRANSAKSI TERAKHIR*\n━━━━━━━━━━━━━━━━━━━━━━\n\n`;

  findTransaction.forEach((tx: ITransaction, index: number) => {
    const icon = tx.type === 'IN' ? '🟢' : '🔴';
    const typeLabel = tx.type === 'IN' ? '[+]' : '[-]';

    const desc = decrypt(tx.description);
    const amt = tx.amount.toLocaleString('id-ID');
    const categoryName = tx.category || (tx.type === TRANSACTION_TYPE.IN ? "Other Income" : "Other Expense");
    const emojiMap = tx.type === TRANSACTION_TYPE.IN
      ? CATEGORY_EMOJIS_INCOME
      : CATEGORY_EMOJIS_EXPENSE;
    const emoji = emojiMap[categoryName as keyof typeof emojiMap] || "📦";
    const categoryLabel = ` [${emoji} ${categoryName}]`;

    const dateString = tx.date.toLocaleString('id-ID', {
      timeZone: 'Asia/Jakarta',
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).replace(/\./g, ':');

    listTeks += `${index + 1}. ${icon} *Rp ${amt}*${categoryLabel}\n`;
    listTeks += `   🕒 _${dateString}_\n`;
    listTeks += `   📝 ${desc} ${typeLabel}\n\n`;
  });

  listTeks += `──────────────────────\n_Gunakan .rekap untuk total bulanan_`;

  await sock.sendMessage(jid, { text: listTeks.trim()});
}