import { Model } from "mongoose";
import WAWebJS from "whatsapp-web.js";

import { TRANSACTION_TYPE } from "../constants";
import { Transaction } from "../models";
import { ITransaction, Rekap, TotalTransactionRekap } from "../types";
import { decrypt } from "./encryption";

const rekapFormat = (month: string, year: string, outgoing: Number, incoming: Number, total: TotalTransactionRekap) => {
  const teksRekap = `
  📊 *REKAPITULASI: ${month.toUpperCase()} ${year}*
  ━━━━━━━━━━━━━━━━━━━━━━

  💰 *DATA KEUANGAN*
  📈 Pemasukan  : *Rp ${incoming.toLocaleString('id-ID')}*
  📉 Pengeluaran : *Rp ${outgoing.toLocaleString('id-ID')}*
  ──────────────────────

  📝 *STATISTIK AKTIVITAS*
  📥 Transaksi Masuk  : ${total.incoming}x
  📤 Transaksi Keluar : ${total.outgoing}x
  🔄 Total Aktivitas  : ${total.total}x

  ━━━━━━━━━━━━━━━━━━━━━━
  _Generated by BudgetBot_
  `.trim();
    

  return teksRekap;
}

export const transactionRecordCurrentMonth = async (
  userId: string,
  message: WAWebJS.Message,
  Transaction: Model<ITransaction>,
) => {
  let pengeluaran = 0;
  let pemasukan = 0;
  let jumlahTransaksiKeluar = 0;
  let jumlahTransaksiMasuk = 0;

  const getDate = new Date();

  const currentMonth = parseInt(getDate.toLocaleString('id-ID', { month: 'numeric', timeZone: 'Asia/Jakarta' }));
  const currentYear = parseInt(getDate.toLocaleString('id-ID', { year: 'numeric', timeZone: 'Asia/Jakarta' }));

  const monthName = getDate.toLocaleString('id-ID', { month: 'long', timeZone: 'Asia/Jakarta' });
  const rekap = await Transaction.aggregate([
    {
      $match: {
        userId,
        $expr: {
          $and: [
            // MongoDB $month mengembalikan angka, jadi kita bandingkan dengan currentMonth (angka)
            { $eq: [{ $month: "$date" }, currentMonth] },
            { $eq: [{ $year: "$date" }, currentYear] }
          ]
        }
      }
    },
    {
      $group: {
        _id: "$type",
        total: { $sum: "$amount" },
        count: { $sum: 1 }
      }
    }
  ]);

  rekap.forEach((item: Rekap) => {
    if (item._id === TRANSACTION_TYPE.OUT) {
      pengeluaran = item.total;
      jumlahTransaksiKeluar = item.count;
    } else if (item._id === TRANSACTION_TYPE.IN) {
      pemasukan = item.total;
      jumlahTransaksiMasuk = item.count;
    };
  });

  const longMonth = getDate.toLocaleString('id-ID', { 
    month: 'long',
    timeZone: 'Asia/Jakarta' 
  });
  const jumlahTransaksi = jumlahTransaksiKeluar + jumlahTransaksiMasuk;

  if (jumlahTransaksi === 0) {
    message.reply(`📭 *Rekap ${longMonth} ${currentYear}*\n\nBelum ada transaksi yang dicatat bulan ini.`);
  } else {
    const totalTransaction = {
      outgoing: jumlahTransaksiKeluar,
      incoming: jumlahTransaksiMasuk,
      total: jumlahTransaksi
    }

    const recordTextFormat = rekapFormat(
      monthName,
      currentYear.toString(),
      pengeluaran,
      pemasukan,
      totalTransaction
    );

    message.reply(recordTextFormat);
  }
}

export const transactionHistoryBy = async (
  userId: string,
  message: WAWebJS.Message,
  match: RegExpMatchArray
) => {
  if(!match) return

  let getLimit = Math.min(parseInt(match[2] || '5'), 20);
  
  const findTransaction = await Transaction.find({userId}).sort({date: -1}).limit(getLimit);

  if (findTransaction.length === 0) {
    return message.reply("📭 Belum ada catatan transaksi.");
  }

  if (findTransaction.length < 5){ 
    getLimit = findTransaction.length
  }

  let listTeks = `📝 *${getLimit} TRANSAKSI TERAKHIR*\n━━━━━━━━━━━━━━━━━━━━━━\n\n`;

  findTransaction.forEach((tx,index) => {
    const icon = tx.type === 'IN' ? '🟢' : '🔴';
    const typeLabel = tx.type === 'IN' ? '[+]' : '[-]';

    const desc = decrypt(tx.description);
    const amt = tx.amount.toLocaleString('id-ID');
    const dateString = tx.date.toLocaleString('id-ID', {
      timeZone: 'Asia/Jakarta',
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).replace(/\./g, ':');
    // Menyusun baris teks
    listTeks += `${index + 1}. ${icon} *Rp ${amt}*\n`;
    listTeks += `   🕒 _${dateString}_\n`;
    listTeks += `   📝 ${desc} ${typeLabel}\n\n`;
  });

  listTeks += `──────────────────────\n_Gunakan .rekap untuk total bulanan_`;

  return await message.reply(listTeks.trim());
}